### PR TITLE
Add GitHub actions workflow

### PR DESCRIPTION
**Pull request by simeg**
Background in #12.

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
lets try this :)

**Comment by simeg** [comment]
Well that's annoying. I wish there was a simple way to pass arguments to the docker container. I'll see what I can do.

**Comment by nikitavoloboev** [comment]
So these builds are failing all the time. I think I will strip the action and perhaps run the tool across all the curated lists as a weekly thing myself.

Unless you have an idea for how to fix it?

**Comment by nikitavoloboev** [comment]
It seems like it's wasting resources to do these checks so many times (on each commit). 🤔

**Comment by nikitavoloboev** [comment]
I removed it for now but I welcome a PR with an instance that works if you have the time ❤️

**Pull request merged**
